import { pgTable, uuid, text, timestamp, integer, boolean, primaryKey, uniqueIndex, index, foreignKey, check, jsonb } from 'drizzle-orm/pg-core';
import { sql } from 'drizzle-orm';
const time = (name: string) => timestamp(name, { withTimezone: true }).notNull().defaultNow();
export const organizations = pgTable('organizations', { id: uuid('id').primaryKey().defaultRandom(), name: text('name').notNull(), status: text('status').notNull().default('ACTIVE'), createdAt: time('created_at'), updatedAt: time('updated_at') }, t => [check('organization_status', sql`${t.status} IN ('ACTIVE','INACTIVE')`)]);
export const users = pgTable('users', { id: uuid('id').primaryKey().defaultRandom(), login: text('login').notNull(), passwordHash: text('password_hash').notNull(), status: text('status').notNull().default('ACTIVE'), createdAt: time('created_at'), updatedAt: time('updated_at'), lastLoginAt: timestamp('last_login_at', { withTimezone: true }) }, t => [uniqueIndex('users_login_unique').on(t.login), check('user_status', sql`${t.status} IN ('ACTIVE','INACTIVE')`)]);
export const memberships = pgTable('organization_memberships', { organizationId: uuid('organization_id').notNull().references(() => organizations.id), userId: uuid('user_id').notNull().references(() => users.id), role: text('role').notNull(), status: text('status').notNull().default('ACTIVE') }, t => [primaryKey({ columns: [t.organizationId, t.userId] }), index('membership_user').on(t.userId), check('membership_role', sql`${t.role} IN ('ADMIN','OPERADOR','VENDEDOR')`), check('membership_status', sql`${t.status} IN ('ACTIVE','INACTIVE')`)]);
export const sessions = pgTable('sessions', { id: uuid('id').primaryKey().defaultRandom(), userId: uuid('user_id').notNull(), organizationId: uuid('organization_id').notNull(), tokenHash: text('session_token_hash').notNull(), csrfHash: text('csrf_hash').notNull(), createdAt: time('created_at'), expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(), revokedAt: timestamp('revoked_at', { withTimezone: true }) }, t => [uniqueIndex('session_token_unique').on(t.tokenHash), index('session_expiry').on(t.expiresAt), foreignKey({ columns: [t.organizationId, t.userId], foreignColumns: [memberships.organizationId, memberships.userId] })]);
export const connections = pgTable('erp_connections', { id: uuid('id').primaryKey().defaultRandom(), organizationId: uuid('organization_id').notNull().references(() => organizations.id), provider: text('provider').notNull().default('TINY'), status: text('status').notNull().default('DISCONNECTED'), accountVerified: boolean('account_verified').notNull().default(false), expectedIdentity: text('expected_identity_encrypted'), verifiedIdentity: text('verified_account_identity'), access: text('access_token_encrypted'), refresh: text('refresh_token_encrypted'), accessExpiresAt: timestamp('access_expires_at', { withTimezone: true }), refreshExpiresAt: timestamp('refresh_expires_at', { withTimezone: true }), connectionGeneration: integer('connection_generation').notNull().default(0), tokenVersion: integer('token_version').notNull().default(0), keyVersion: text('encryption_key_version'), refreshLease: uuid('refresh_lease'), refreshLeaseUntil: timestamp('refresh_lease_until', { withTimezone: true }), readLease: uuid('read_lease'), readLeaseUntil: timestamp('read_lease_until', { withTimezone: true }), pauseUntil: timestamp('pause_until', { withTimezone: true }), connectedAt: timestamp('connected_at', { withTimezone: true }), updatedAt: time('updated_at'), disconnectedAt: timestamp('disconnected_at', { withTimezone: true }) }, t => [uniqueIndex('organization_provider_unique').on(t.organizationId, t.provider), check('tiny_provider', sql`${t.provider} = 'TINY'`), check('connection_status', sql`${t.status} IN ('DISCONNECTED','CONNECTING','CONNECTED','REAUTH_REQUIRED','ACCOUNT_MISMATCH','ERROR')`), check('verified_connected', sql`${t.status} <> 'CONNECTED' OR ${t.accountVerified} = true`)]);
export const attempts = pgTable('oauth_attempts', { id: uuid('id').primaryKey().defaultRandom(), organizationId: uuid('organization_id').notNull(), userId: uuid('initiated_by_user_id').notNull(), sessionId: uuid('session_id').notNull().references(() => sessions.id), stateHash: text('state_hash').notNull(), verifier: text('code_verifier_encrypted').notNull(), connectionVersion: integer('connection_version').notNull(), expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(), consumedAt: timestamp('consumed_at', { withTimezone: true }), createdAt: time('created_at') }, t => [uniqueIndex('oauth_state_unique').on(t.stateHash), index('oauth_expiry').on(t.expiresAt), foreignKey({ columns: [t.organizationId, t.userId], foreignColumns: [memberships.organizationId, memberships.userId] })]);
export const audit = pgTable('audit_events', { id: uuid('id').primaryKey().defaultRandom(), organizationId: uuid('organization_id').notNull().references(() => organizations.id), userId: uuid('user_id').references(() => users.id), action: text('action').notNull(), result: text('result').notNull(), correlationId: uuid('correlation_id').notNull(), createdAt: time('created_at') }, t => [index('audit_org_time').on(t.organizationId, t.createdAt)]);
export const loginLimits = pgTable('login_limits', { key: text('key').primaryKey(), count: integer('count').notNull(), expiresAt: timestamp('expires_at', { withTimezone: true }).notNull() });

// Catalogue staging is immutable once published; tenant FKs also protect internal mistakes.
export const catalogSnapshots = pgTable('catalog_snapshots', {
  id: uuid('id').primaryKey().defaultRandom(), organizationId: uuid('organization_id').notNull().references(() => organizations.id),
  provider: text('provider').notNull().default('TINY'), mode: text('mode').notNull(), status: text('status').notNull().default('BUILDING'),
  commercial: text('commercial').notNull().default('PENDING'), createdAt: time('created_at'), publishedAt: timestamp('published_at', { withTimezone: true }),
  manifest: jsonb('manifest').notNull().default({}), checksum: text('checksum'), anomalies: jsonb('anomalies').notNull().default([]),
}, t => [uniqueIndex('snapshot_tenant_id').on(t.organizationId, t.id), uniqueIndex('one_active_catalog').on(t.organizationId, t.provider).where(sql`${t.status}='ACTIVE'`),
  check('snapshot_provider', sql`${t.provider}='TINY'`), check('snapshot_mode', sql`${t.mode} IN ('FIXTURE','REAL')`),
  check('snapshot_status', sql`${t.status} IN ('BUILDING','VALIDATING','INCOMPLETE','READY','ACTIVE','SUPERSEDED','REJECTED')`),
  check('snapshot_commercial', sql`${t.commercial} IN ('PENDING','SYNTHETIC_ONLY')`)]);
export const catalogHeads = pgTable('catalog_heads', { organizationId: uuid('organization_id').primaryKey().references(() => organizations.id), snapshotId: uuid('snapshot_id').notNull(), revision: integer('revision').notNull().default(1) },
  t => [foreignKey({ columns: [t.organizationId,t.snapshotId], foreignColumns: [catalogSnapshots.organizationId,catalogSnapshots.id] }),check('head_revision',sql`${t.revision}>0`)]);
export const catalogEntries = pgTable('catalog_entries', { organizationId: uuid('organization_id').notNull(), snapshotId: uuid('snapshot_id').notNull(), resource: text('resource').notNull(), erpId: text('erp_id').notNull(), projection: jsonb('projection').notNull(), contentHash: text('content_hash').notNull(), commercial: text('commercial').notNull().default('PENDING') },
  t => [primaryKey({ columns: [t.organizationId,t.snapshotId,t.resource,t.erpId] }), foreignKey({ columns: [t.organizationId,t.snapshotId], foreignColumns: [catalogSnapshots.organizationId,catalogSnapshots.id] }),check('entry_resource',sql`${t.resource} IN ('products','contacts','sellers','priceLists')`)]);
export const catalogQuarantine = pgTable('catalog_quarantine', { id: uuid('id').primaryKey().defaultRandom(), organizationId: uuid('organization_id').notNull(), snapshotId: uuid('snapshot_id').notNull(), resource: text('resource').notNull(), erpId: text('erp_id'), reason: text('reason').notNull(), stage: text('stage').notNull(), resolved: boolean('resolved').notNull().default(false), createdAt: time('created_at') },
  t => [foreignKey({ columns: [t.organizationId,t.snapshotId], foreignColumns: [catalogSnapshots.organizationId,catalogSnapshots.id] }), index('quarantine_snapshot').on(t.organizationId,t.snapshotId)]);
export const syncJobs = pgTable('sync_jobs', { id: uuid('id').primaryKey().defaultRandom(), organizationId: uuid('organization_id').notNull(), requestedBy: uuid('requested_by').notNull(), snapshotId: uuid('snapshot_id').notNull(), mode: text('mode').notNull(), resource: text('resource').notNull().default('ALL'), status: text('status').notNull().default('PENDING'),
  checkpoint: jsonb('checkpoint').notNull().default({}), pages: integer('pages_processed').notNull().default(0), received: integer('records_received').notNull().default(0), validated: integer('records_validated').notNull().default(0), quarantined: integer('records_quarantined').notNull().default(0), attempts: integer('attempt_count').notNull().default(0),
  executionId: uuid('execution_id'), leaseUntil: timestamp('lease_until',{withTimezone:true}), retryAfter: timestamp('retry_after',{withTimezone:true}), errorCode:text('error_code'), connectionVersion: integer('connection_version'), accountKey:text('account_key'), baseline: uuid('baseline_snapshot_id'), createdAt:time('created_at'),startedAt:timestamp('started_at',{withTimezone:true}),finishedAt:timestamp('finished_at',{withTimezone:true}) },
  t => [foreignKey({ columns:[t.organizationId,t.requestedBy],foreignColumns:[memberships.organizationId,memberships.userId]}),foreignKey({columns:[t.organizationId,t.snapshotId],foreignColumns:[catalogSnapshots.organizationId,catalogSnapshots.id]}),
    uniqueIndex('one_sync_per_organization').on(t.organizationId).where(sql`${t.status} IN ('PENDING','RUNNING','PAUSED','RETRY_WAIT')`),
    check('job_status',sql`${t.status} IN ('PENDING','RUNNING','PAUSED','RETRY_WAIT','COMPLETED','FAILED','CANCELLED')`),check('job_mode',sql`${t.mode} IN ('FIXTURE','REAL')`),check('job_counts',sql`${t.pages}>=0 AND ${t.received}>=0 AND ${t.validated}>=0 AND ${t.quarantined}>=0 AND ${t.attempts}>=0`)]);
export const syncBudgets = pgTable('sync_budgets', { key:text('key').primaryKey(), nextAt:time('next_at'), pauseUntil:timestamp('pause_until',{withTimezone:true}), lease:uuid('lease'),leaseUntil:timestamp('lease_until',{withTimezone:true}),remaining:integer('remaining'),resetAt:timestamp('reset_at',{withTimezone:true}) });
export const syncWatermarks = pgTable('sync_watermarks',{organizationId:uuid('organization_id').notNull().references(()=>organizations.id),resource:text('resource').notNull(),watermark:timestamp('watermark',{withTimezone:true}),semanticsVerified:boolean('semantics_verified').notNull().default(false),overlapSeconds:integer('overlap_seconds').notNull().default(300)},t=>[primaryKey({columns:[t.organizationId,t.resource]}),check('watermark_overlap',sql`${t.overlapSeconds}>0`)]);
