import {pgTable,uuid,text,timestamp,integer,boolean,jsonb,primaryKey,uniqueIndex,index,foreignKey,customType} from 'drizzle-orm/pg-core';
import {sql} from 'drizzle-orm';
import {organizations,memberships,sessions} from './schema.ts';
const bytea=customType<{data:Buffer}>({dataType:()=> 'bytea'});
const time=(name:string)=>timestamp(name,{withTimezone:true}).notNull().defaultNow();
// SQL migration 0003 owns checks, triggers, deferred circular FKs and privileged functions.
// These declarations expose the tables to the ORM; no ORM writes are granted to the runtime.
export const submissionOrders=pgTable('submission_orders',{
 organizationId:uuid('organization_id').notNull().references(()=>organizations.id),orderId:uuid('order_id').notNull().defaultRandom(),originLocalOrderId:text('origin_local_order_id').notNull(),ownerId:uuid('owner_id').notNull(),orderRevision:integer('order_revision').notNull().default(0),anchorRevision:integer('anchor_revision').notNull().default(1),eventSequence:integer('event_sequence').notNull().default(0),currentSubmissionId:uuid('current_submission_id'),acceptedSubmissionId:uuid('accepted_submission_id'),conflictHold:boolean('conflict_hold').notNull().default(false),recoveryHold:boolean('recovery_hold').notNull().default(false),createdAt:time('created_at'),updatedAt:time('updated_at'),
},t=>[primaryKey({columns:[t.organizationId,t.orderId]}),uniqueIndex('submission_origin_unique').on(t.organizationId,t.originLocalOrderId),foreignKey({columns:[t.organizationId,t.ownerId],foreignColumns:[memberships.organizationId,memberships.userId]}),index('submission_owner').on(t.organizationId,t.ownerId)]);
export const orderSubmissions=pgTable('order_submissions',{
 organizationId:uuid('organization_id').notNull(),orderId:uuid('order_id').notNull(),submissionId:uuid('submission_id').notNull(),orderRevision:integer('order_revision').notNull(),sourceLocalRevision:integer('source_local_revision').notNull(),snapshotEncrypted:bytea('snapshot_encrypted').notNull(),requestEncrypted:bytea('request_encrypted').notNull(),businessHash:text('business_hash').notNull(),requestHash:text('request_hash').notNull(),byteLength:integer('byte_length').notNull(),contractVersion:text('contract_version').notNull(),canonicalVersion:text('canonical_version').notNull(),mapperVersion:text('mapper_version').notNull(),mode:text('mode').notNull(),provider:text('provider').notNull(),targetAccount:text('target_account').notNull(),connectionId:uuid('connection_id'),connectionGeneration:integer('connection_generation').notNull(),admittedBy:uuid('admitted_by').notNull(),state:text('state').notNull(),certainty:text('certainty').notNull(),ledgerRevision:integer('ledger_revision').notNull().default(1),conflictHold:boolean('conflict_hold').notNull().default(false),externalOrderId:text('external_order_id'),acceptedEvidenceId:uuid('accepted_evidence_id'),lastEvidenceId:uuid('last_evidence_id'),releasedAt:timestamp('released_at',{withTimezone:true}),retryAt:timestamp('retry_at',{withTimezone:true}),createdAt:time('created_at'),updatedAt:time('updated_at'),
},t=>[primaryKey({columns:[t.organizationId,t.submissionId]}),uniqueIndex('submission_context_unique').on(t.organizationId,t.orderId,t.submissionId),foreignKey({columns:[t.organizationId,t.orderId],foreignColumns:[submissionOrders.organizationId,submissionOrders.orderId]}),foreignKey({columns:[t.organizationId,t.admittedBy],foreignColumns:[memberships.organizationId,memberships.userId]}),uniqueIndex('submission_one_occupant').on(t.organizationId,t.orderId).where(sql`${t.releasedAt} IS NULL`),uniqueIndex('submission_external_unique').on(t.organizationId,t.provider,t.targetAccount,t.externalOrderId).where(sql`${t.externalOrderId} IS NOT NULL`),index('submission_pending').on(t.organizationId,t.state,t.updatedAt),index('submission_history').on(t.organizationId,t.orderId,t.createdAt)]);
export const submissionCommunications=pgTable('submission_communications',{
 organizationId:uuid('organization_id').notNull(),orderId:uuid('order_id').notNull(),submissionId:uuid('submission_id').notNull(),operationId:uuid('operation_id').notNull(),executionId:uuid('execution_id').notNull(),sequence:integer('sequence').notNull(),kind:text('kind').notNull(),outcome:text('outcome').notNull(),potentialEffect:boolean('potential_effect').notNull(),safeClosedAt:timestamp('safe_closed_at',{withTimezone:true}),closedEvidenceId:uuid('closed_evidence_id'),leaseUntil:timestamp('lease_until',{withTimezone:true}).notNull(),finishedAt:timestamp('finished_at',{withTimezone:true}),abandoned:boolean('abandoned').notNull().default(false),authorizedBy:uuid('authorized_by').notNull(),authorizedSessionId:uuid('authorized_session_id').notNull().references(()=>sessions.id),createdAt:time('created_at'),
},t=>[primaryKey({columns:[t.organizationId,t.operationId]}),uniqueIndex('communication_context_unique').on(t.organizationId,t.orderId,t.submissionId,t.operationId),uniqueIndex('communication_execution_unique').on(t.organizationId,t.executionId),uniqueIndex('communication_sequence_unique').on(t.organizationId,t.submissionId,t.sequence),foreignKey({columns:[t.organizationId,t.orderId,t.submissionId],foreignColumns:[orderSubmissions.organizationId,orderSubmissions.orderId,orderSubmissions.submissionId]}),foreignKey({columns:[t.organizationId,t.authorizedBy],foreignColumns:[memberships.organizationId,memberships.userId]}),uniqueIndex('submission_one_capable').on(t.organizationId,t.submissionId).where(sql`${t.kind}='CREATE' AND (${t.potentialEffect} OR ${t.outcome} IN ('PENDING','INCONCLUSIVE','CONFLICT'))`),uniqueIndex('submission_one_lookup').on(t.organizationId,t.submissionId).where(sql`${t.kind}='LOOKUP' AND ${t.finishedAt} IS NULL`),index('submission_recovery').on(t.organizationId,t.createdAt).where(sql`${t.kind}='CREATE' AND ${t.potentialEffect}`)]);
export const submissionEvidence=pgTable('submission_evidence',{
 organizationId:uuid('organization_id').notNull(),orderId:uuid('order_id').notNull(),submissionId:uuid('submission_id').notNull(),evidenceId:uuid('evidence_id').notNull(),operationId:uuid('operation_id').notNull(),executionId:uuid('execution_id').notNull(),source:text('source').notNull(),conclusion:text('conclusion').notNull(),businessHash:text('business_hash').notNull(),requestHash:text('request_hash').notNull(),targetAccount:text('target_account').notNull(),connectionGeneration:integer('connection_generation').notNull(),externalOrderId:text('external_order_id'),checks:jsonb('checks').notNull(),contentRejected:boolean('content_rejected').notNull().default(false),detailsEncrypted:bytea('details_encrypted').notNull(),detailsHash:text('details_hash').notNull(),authorId:uuid('author_id').notNull(),observedAt:time('observed_at'),receivedAt:time('received_at'),
},t=>[primaryKey({columns:[t.organizationId,t.evidenceId]}),uniqueIndex('evidence_context_unique').on(t.organizationId,t.orderId,t.submissionId,t.evidenceId),foreignKey({columns:[t.organizationId,t.orderId,t.submissionId],foreignColumns:[orderSubmissions.organizationId,orderSubmissions.orderId,orderSubmissions.submissionId]}),foreignKey({columns:[t.organizationId,t.orderId,t.submissionId,t.operationId],foreignColumns:[submissionCommunications.organizationId,submissionCommunications.orderId,submissionCommunications.submissionId,submissionCommunications.operationId]}),foreignKey({columns:[t.organizationId,t.authorId],foreignColumns:[memberships.organizationId,memberships.userId]})]);
export const submissionEvents=pgTable('submission_events',{
 organizationId:uuid('organization_id').notNull(),orderId:uuid('order_id').notNull(),eventId:uuid('event_id').notNull().defaultRandom(),submissionId:uuid('submission_id'),sequence:integer('sequence').notNull(),action:text('action').notNull(),actorId:uuid('actor_id').notNull(),sessionId:uuid('session_id').notNull().references(()=>sessions.id),commandId:uuid('command_id'),commandDigest:text('command_digest'),commandReceipt:jsonb('command_receipt'),evidenceId:uuid('evidence_id'),fromState:text('from_state'),toState:text('to_state'),createdAt:time('created_at'),
},t=>[primaryKey({columns:[t.organizationId,t.eventId]}),uniqueIndex('event_sequence_unique').on(t.organizationId,t.orderId,t.sequence),uniqueIndex('event_command_unique').on(t.organizationId,t.commandId),foreignKey({columns:[t.organizationId,t.orderId],foreignColumns:[submissionOrders.organizationId,submissionOrders.orderId]}),foreignKey({columns:[t.organizationId,t.orderId,t.submissionId],foreignColumns:[orderSubmissions.organizationId,orderSubmissions.orderId,orderSubmissions.submissionId]}),foreignKey({columns:[t.organizationId,t.orderId,t.submissionId,t.evidenceId],foreignColumns:[submissionEvidence.organizationId,submissionEvidence.orderId,submissionEvidence.submissionId,submissionEvidence.evidenceId]}),foreignKey({columns:[t.organizationId,t.actorId],foreignColumns:[memberships.organizationId,memberships.userId]})]);
