'use client';
import { useCallback, useRef, useState } from 'react';
import { LocalCatalog, type CatalogTimings } from '@/services/catalog-client';
import { syntheticCatalogScope, syntheticCatalogTransport } from '@/services/catalog-fixture';
import { IndexedCatalogCache, type CatalogEntry } from '@/repositories/catalog-cache';
import { LocalAutocomplete } from './local-autocomplete';
import { PersistenceLab } from './persistence-lab';
export function CatalogLab(){
 const catalog=useRef<LocalCatalog|null>(null),[query,setQuery]=useState(''),[selected,setSelected]=useState<CatalogEntry|null>(null),[message,setMessage]=useState('Carregue um catálogo sintético. Nenhuma conexão com Tiny ou backend é feita.'),[version,setVersion]=useState<string|null>(null),[pending,setPending]=useState<string|null>(null),[timings,setTimings]=useState<CatalogTimings[]>([]),[busy,setBusy]=useState(false);
 const client=()=>catalog.current??(catalog.current=new LocalCatalog(syntheticCatalogScope,new IndexedCatalogCache('atram-catalog-diagnostico-v1')));
 const background=useCallback(async()=>{
  const c=catalog.current??(catalog.current=new LocalCatalog(syntheticCatalogScope,new IndexedCatalogCache('atram-catalog-diagnostico-v1'))),transport=await syntheticCatalogTransport(5),result=await c.update(transport);
  if(result){setTimings(rows=>[...rows.slice(-35),result]);setPending(c.pendingVersion);}return result;
 },[]);
 const search=useCallback((text:string):Array<CatalogEntry&{id:string}>=>(catalog.current?.search(text)??[]).map(item=>({...item,id:item.erpId})),[]);
 async function load(){setBusy(true);try{await background();setMessage('Nova versão íntegra disponível. Limpe a pesquisa e a seleção antes de aplicar.');}catch{setMessage('Não foi possível atualizar. A versão anterior foi preservada.');}finally{setBusy(false);}}
 async function recover(){setBusy(true);try{const c=client(),ok=await c.recover(true);setVersion(c.version);setMessage(ok?'Catálogo recuperado do IndexedDB, sem rede.':'Não há catálogo sintético válido para recuperação.');}catch{setMessage('Cache inválido ou indisponível; recarregue a fixture.');}finally{setBusy(false);}}
 function activate(){const c=client(),start=performance.now();if(c.activate({query,selection:!!selected,editing:false})){setVersion(c.version);setPending(c.pendingVersion);setTimings(rows=>rows.map(r=>r.version===c.version?{...r,activationMs:performance.now()-start}:r));setMessage('Versão aplicada. Itens existentes do pedido permanecem capturados.');}else setMessage('Limpe a pesquisa e a seleção para aplicar a versão disponível.');}
 function exportReport(){const payload={recordedAt:new Date().toISOString(),fixtureProducts:900,realTinyCalls:0,method:'Transferência sintética paginada, SHA-256, índice local e IndexedDB medidos separadamente. A matriz de pedidos abaixo exporta UI/React e autosave em seu próprio JSON.',timings};const url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'})),link=document.createElement('a');link.href=url;link.download='atram-catalogo-etapa7b3.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <><section className="submission-panel"><h2>Prévia técnica local</h2><p>Somente fixtures públicas. Dados reais, aprovação comercial e envio ao ERP permanecem indisponíveis. Pesquisa local por código, GTIN, descrição e marca; registros bloqueados são identificados.</p><div className="lab-controls"><button disabled={busy} className="button primary" onClick={()=>void load()}>Preparar 900 produtos</button><button disabled={busy} className="button secondary" onClick={activate}>Aplicar versão disponível</button><button disabled={busy} className="button secondary" onClick={()=>void recover()}>Recuperar catálogo offline</button><button className="button secondary" onClick={()=>{setQuery('');setSelected(null);}}>Limpar pesquisa e seleção</button><button className="button secondary" onClick={()=>void client().logout().then(()=>{setVersion(null);setPending(null);setSelected(null);setQuery('');setMessage('Catálogo desta sessão sintética removido. Rascunhos preservados.');})}>Encerrar sessão sintética</button><button className="button secondary" onClick={exportReport}>Exportar tempos do catálogo</button></div><p role="status">{message}</p><p>Versão ativa: {version??'nenhuma'} · Nova versão: {pending??'nenhuma'}</p><LocalAutocomplete id="catalog-preview-search" label="Pesquisar catálogo técnico" placeholder="Código, GTIN, descrição ou marca" value={query} onChange={text=>{setQuery(text);setSelected(null);}} search={search} onSelect={item=>{setSelected(item);setQuery(String(item.name));}} render={item=><><strong>{String(item.name)}</strong><span>{String(item.code)} · {String(item.unitOriginal)} · {item.commercial}</span></>} />{selected&&<p>Selecionado: {String(selected.name)} · unidade {String(selected.unitOriginal)} · {selected.commercial}. Esta seleção não cria pedido real.</p>}{timings.length>0&&<div className="lab-results"><table aria-label="Tempos do catálogo"><thead><tr><th>Transferência ms</th><th>Integridade ms</th><th>Índice ms</th><th>IndexedDB ms</th><th>Ativação ms</th></tr></thead><tbody>{timings.map(t=><tr key={t.version}><td>{t.transferMs.toFixed(2)}</td><td>{t.verificationMs.toFixed(2)}</td><td>{t.indexMs.toFixed(2)}</td><td>{t.indexedDbMs.toFixed(2)}</td><td>{t.activationMs.toFixed(2)}</td></tr>)}</tbody></table></div>}</section><PersistenceLab backgroundWork={background} /></>;
}
