'use client';

import { CreditCard, Link2, Percent, Landmark, FileText, Truck, MessageSquare, CircleDashed } from 'lucide-react';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Checkbox } from '@/components/ui/checkbox';
import { paymentMethods, shippingMethods } from '@/domain/mock-data';
import { memo } from 'react';
import type { OrderFields, FieldsChange } from '@/hooks/use-draft-order';
import { ChoiceField, TextField, Unavailable } from './fields';

const tabs = [
  { id: 'payment', label: 'Pagamento', icon: CreditCard },
  { id: 'integrated', label: 'Pagamento integrado', icon: Link2 },
  { id: 'commission', label: 'Comissões', icon: Percent },
  { id: 'taxes', label: 'Impostos', icon: Landmark },
  { id: 'new-taxes', label: 'Novos Tributos', icon: FileText },
  { id: 'shipping', label: 'Transportador / Volumes', icon: Truck },
  { id: 'notes', label: 'Observações', icon: MessageSquare },
];

export const OrderTabs = memo(function OrderTabs({ fields, onChange }: { fields: OrderFields; onChange: (patch: FieldsChange) => void }) {
  return <Tabs defaultValue="payment" className="order-tabs section-card"><div className="tabs-scroll"><TabsList variant="line" className="order-tab-list" aria-label="Informações complementares do pedido">{tabs.map(({ id, label, icon: Icon }) => <TabsTrigger key={id} value={id} className="order-tab"><Icon />{label}</TabsTrigger>)}</TabsList></div>
    <TabsContent value="payment" forceMount className="order-tab-panel"><div className="payment-fields"><ChoiceField label="Forma de recebimento" options={paymentMethods} value={fields.payment.method} onValueChange={value => onChange({ payment: { ...fields.payment, method: value } })} /><ChoiceField label="Meio" options={['Banco', 'Carteira']} value={fields.payment.channel} onValueChange={value => onChange({ payment: { ...fields.payment, channel: value } })} /><ChoiceField label="Conta bancária" options={['Itaú', 'Banco Exemplo']} value={fields.payment.bank} onValueChange={value => onChange({ payment: { ...fields.payment, bank: value } })} /><ChoiceField label="Categoria" options={['Vendas', 'Vendas a prazo']} value={fields.payment.category} onValueChange={value => onChange({ payment: { ...fields.payment, category: value } })} /></div><div className="payment-terms"><TextField label="Condição de pagamento" value={fields.payment.terms} onChange={e => onChange({ payment: { ...fields.payment, terms: e.target.value } })} placeholder="Ex.: 30 60 90" /><Unavailable message="A geração de parcelas será implementada em uma etapa posterior."><button className="button secondary" disabled>Gerar parcelas</button></Unavailable><span>Exemplos: 30 · 30 60 · 3x · 15 + 2x</span></div></TabsContent>
    <TabsContent value="integrated" className="order-tab-panel"><div className="tab-placeholder"><CircleDashed /><div><strong>Pagamento integrado</strong><p>Área reservada. Nenhuma conexão com meios de pagamento nesta etapa.</p></div></div></TabsContent>
    <TabsContent value="commission" className="order-tab-panel"><div className="tab-placeholder"><Percent /><div><strong>Comissões</strong><p>Área reservada para as condições comerciais do vendedor.</p></div></div></TabsContent>
    <TabsContent value="taxes" className="order-tab-panel"><div className="tax-preview">{['IPI', 'ICMS ST + FCP ST', 'ICMS + FCP', 'PIS', 'COFINS', 'DIFAL'].map(tax => <TextField key={tax} label={tax} defaultValue="R$ 0,00" readOnly />)}</div><p className="form-footnote">Valores ilustrativos. Nenhum cálculo fiscal é realizado.</p></TabsContent>
    <TabsContent value="new-taxes" className="order-tab-panel"><div className="tax-preview">{['IBS Estadual', 'IBS Municipal', 'CBS'].map(tax => <TextField key={tax} label={tax} defaultValue="R$ 0,00" readOnly />)}</div><p className="form-footnote">Campos reservados para implementação futura.</p></TabsContent>
    <TabsContent value="shipping" forceMount className="order-tab-panel"><div className="shipping-fields"><ChoiceField label="Forma de envio" options={shippingMethods} value={fields.shipping.method} onValueChange={value => onChange({ shipping: { ...fields.shipping, method: value } })} /><ChoiceField label="Forma de frete" options={['Normal', 'Expresso']} value={fields.shipping.freightType} onValueChange={value => onChange({ shipping: { ...fields.shipping, freightType: value } })} /><ChoiceField label="Frete por conta" options={['Remetente', 'Destinatário', 'Sem frete']} value={fields.shipping.payer} onValueChange={value => onChange({ shipping: { ...fields.shipping, payer: value } })} /><TextField label="Transportadora" value={fields.shipping.carrier} onChange={e => onChange({ shipping: { ...fields.shipping, carrier: e.target.value } })} placeholder="Nome da transportadora" /><TextField label="Código de rastreamento" value={fields.shipping.trackingCode} onChange={e => onChange({ shipping: { ...fields.shipping, trackingCode: e.target.value } })} placeholder="Opcional" /><TextField label="URL de rastreamento" value={fields.shipping.trackingUrl} onChange={e => onChange({ shipping: { ...fields.shipping, trackingUrl: e.target.value } })} placeholder="https://" type="url" /><TextField label="Quantidade de volumes" value={fields.shipping.volumes} onChange={e => onChange({ shipping: { ...fields.shipping, volumes: Math.max(0, Number(e.target.value) || 0) } })} type="number" min="0" step="1" /><label className="checkbox-label"><Checkbox id="dispatch" checked={fields.shipping.sendToDispatch} onCheckedChange={checked => onChange({ shipping: { ...fields.shipping, sendToDispatch: checked === true } })} />Enviar para expedição</label></div></TabsContent>
    <TabsContent value="notes" forceMount className="order-tab-panel"><div className="notes-fields"><div className="field"><label htmlFor="public-notes">Observações</label><textarea id="public-notes" value={fields.notes} onChange={e => onChange({ notes: e.target.value })} placeholder="Informações que acompanham o pedido..." rows={3} /></div><div className="field"><label htmlFor="internal-notes">Observações internas</label><textarea id="internal-notes" value={fields.internalNotes} onChange={e => onChange({ internalNotes: e.target.value })} placeholder="Anotações para a equipe..." rows={3} /></div></div></TabsContent>
  </Tabs>;
});
